### PR TITLE
Improving placeholders

### PR DESCRIPTION
**Pull request by superalex**
Depends on https://github.com/taigaio/taiga-back/pull/464

It still needs some love from @Xaviju the three places where we need your magic have the string "TODO PLACEHOLDER" ;)

### CODE REVIEW

**Comment by superalex** [comment]
- The show/hide tags isn't updating the text correctly. I think those buttons shouldn't appear if there are no stories in the backlog.

- Can't drag us from sprint to an empty backlog

- In backlog the placeholder isn't shown if there is only one user story without tasks

- In Kanban the placeholder text isn't correctly, it says "this could be a task", kanban works with user stories.

**Comment by Xaviju** [comment]
- [x] The show/hide tags isn't updating the text correctly. I think those buttons shouldn't appear if there are no stories in the backlog.
- [ ] Can't drag us from sprint to an empty backlog
- [ ] In backlog the placeholder isn't shown if there is only one user story without tasks
- [ ] In Kanban the placeholder text isn't correctly, it says "this could be a task", kanban works with user stories.
- [ ] In issues the placeholder for "no issues" is visually broken

**Comment by Xaviju** [comment]
Cannot fix the broken drag problem, I'll let @juanfran check it.

**Comment by juanfran** [comment]
done!

**Comment by superalex** [comment]
Is it "ready to merge" again?, can I test it?

**Comment by Xaviju** [comment]
We should rebase master before testing it again. Ill do it!

**Comment by superalex** [comment]
Now everything is working ok except in the taskboard, lightbox for us edition isn't working

**Comment by Xaviju** [comment]
:dancers: dancers: dancers: dancers: dancers:

**Pull request merged**
