### PR TITLE
Jwir3/blocking tickets theme

### LINKED ISSUE #1761: Hovering over US that have a blocked status has an ugly green text on red background
**Do you want to request a *feature* or report a *bug*?**
Report a design bug.

**What is the current behavior?**
When a user story is in the "blocked" state, they show up on the kanban board and the taskboard with a red background. When users hover over the title of the US, the color of the text changes to the taiga primary color, which is a green color, resulting in an ugly contrast.

### PR DESCRIPTION
**Pull request by jwir3**
Fixes #1761

### CODE REVIEW

**Comment by jwir3** [comment]
@alexhermida Review ping?

**Comment by alexhermida** [comment]
@jwir3 if you provide us some screenshot, it's easier to comment within the team. Thank you again! 😄

**Comment by jwir3** [comment]
@alexhermida Here's a screenshot of the new title theme for blocked tickets. Instead of the dark green, it uses a dark red.

screenshot-blocked

**Comment by jwir3** [comment]
@alexhermida Review ping

**Comment by jwir3** [comment]
@alexhermida review ping?

**Comment by jwir3** [comment]
@juanfran Would you mind reviewing this PR? I can rebase it to the tip of master so changes are merged if necessary. I'd like to get this merged so my instance of Taiga on my machine can be updated with all the latest changes.

**Comment by yamila-moreno** [comment]
Hi @jwir3 , we have been doing some housecleaning work prior to Taiga6 upcoming release and we are rejecting old PRs that we didn't correctly attend back them. Since Taiga6 bring a signfiicant UX/UI reword, we encourage you to wait and see if Taiga6 satisfies this need and propose a new PR if that's not the case. This time we will make sure to review it when it comes through. Thank you very much (again ^_^ !!!) on behalf of the Taiga Team!

**Pull request closed without merging**
