### PR TITLE
Fix task completed title width

### PR DESCRIPTION
**Pull request by astagi**

### CODE REVIEW

**Comment by Xaviju** [comment]
Sorry I can not merge it because I do not understand what is this exactly fixing, can you please provide a description for the issue?

**Comment by astagi** [comment]
Yes, I provided a fixes width because tasks completed title was on two lines when user story was created , something like

0/0 tasks
Completed

**Comment by Xaviju** [comment]
Can you please provide a screenshot? I cannot reproduce it!
Also browser and OS.
It's weird because sidebar (parent) has a fixed width (over 300px) so this text should never be on two lines. Adding a width to a span that shouldn't need it does not seems to be the best solution. Could this be a bug?

**Comment by Xaviju** [comment]
Ok we reproduced it! Let me find out why its happening :)

**Comment by astagi** [comment]
I noticed that setting width to 80% - 100% of the current progress put that span in a row..

    <div style="width:100%" class="current-progress">
        <span class="tasks-completed">0/0 tasks completed</span>
    </div>

Mac OSX 10.9.5 with Chrome

screen shot 2015-02-03 at 09 25 48

**Comment by astagi** [comment]
Oh ok :) let me know!

**Comment by Xaviju** [comment]
**It seems to me that you actually found a bug!**

This span tasks-completed
```html
<div style="width:100%" class="current-progress">
    <span class="tasks-completed">0/0 tasks completed</span>
</div>
```
Could be a div and **should not be a child of 'current-progress'**

```html
<div style="width:100%" class="current-progress"></div>
<div class="tasks-completed">0/0 tasks completed</div>
```
If you want to fix it you can edit the file *app/partials/us/us-task-progress.jade* please remove the CSS fix :)

:+1:

**Comment by astagi** [comment]
Oh I see... Done, hope it's ok now :) thanks

**Comment by Xaviju** [comment]
Thanks! :+1:

**Comment by astagi** [comment]
yw :)

**Pull request merged**
