### PR TITLE
Revert "Remove robots.txt"

### PR DESCRIPTION
**Pull request by arno01**
This reverts commit e1f99eb592d4638d8ecc7caf3931747c973b0bbb.

Not sure why the robots were removed in past, but here are the traces:
https://github.com/taigaio/taiga-front/pull/493#issuecomment-110616329
https://github.com/taigaio/taiga-front/pull/493/commits/e1f99eb592d4638d8ecc7caf3931747c973b0bbb

### CODE REVIEW

**Comment by bameda** [comment]
This file was removed because sysadmins are responsible for deciding whether they want to add a robots.txt or not, and not Taiga app.

**Comment by bameda** [comment]
However @arno01 thanks for your contribution

**Comment by arno01** [comment]
@bameda that is correct, how about to have at least the empty `/robots.txt` file so that admins would at least were able to find where is this file located? :-)

**Comment by bameda** [comment]
@arno01 ummm the problem is that if someone edit the empty file when you try to upgrade the taiga-front repository (git pull) you could find a conflict in this file.

On the other hand taiga-front is a single-page application so you need a sitemap and something like [Prerender](https://github.com/prerender/prerender) to make scan easier for spiders.

For example, for taiga.io wi have this robot.txt: https://tree.taiga.io/robots.txt with this sitemap: https://api.taiga.io/front/sitemap.xml and we use prerender with a specific nginx configuration https://gist.github.com/thoop/8165802.

**Comment by arno01** [comment]
(_scratching his head_) humm, and how I've missed that...

Thank you for this very complete answer, @bameda ! :-)

**Comment by bameda** [comment]
Thanks to you. :-)

**Pull request closed without merging**
