### PR TITLE
Kanban filters

### PR DESCRIPTION
**Pull request by ahhhkah**
Hi,

I added a filter to the kanban board, because we need this in our company to work efficiently. This is mostly a copy of the backlog-filter with some adjustments. 

screenshot_taiga

Looking forward to your feedback. Thank you in advance!

### CODE REVIEW

**Comment by Xaviju** [comment]
@ahhhkah thanks for your PR. Since this is a very big Story, we still have to do the common process for every user story in our Taiga kanban. 
I moved the User Story we already had to 'ready', referenced this pull request, and the UX team will start working on it as soon as possible. https://tree.taiga.io/project/taiga/us/1775

Thanks again for the PR! :+1:

**Comment by oderwat** [comment]
I comment to put an :+1: on this feature. My company did most of the german translation for Taiga and we can't use it with clients until the Kanban Board can be filtered by tags. We are stuck with Trello for know, because of this single feature (it seems).

**Comment by rwam** [comment]
This feature would be great. +1

**Comment by Feanaur** [comment]
We really need this one :)

**Comment by fpytloun** [comment]
We need this as well, any will to process this 4 months old pull request?

**Comment by daneel23** [comment]
Hi, without this feature value of Taiga is much lower.

Is there any other way to filter tasks/issues assigned to me in a nice, prioritized/state-ordered manner? Am I missing something?

**Comment by eskaaren** [comment]
New Taiga user here, this is the one feature I really need so :+1:

**Comment by DanMMX** [comment]
Is this feature going to be available anytime soon?

**Comment by bameda** [comment]
We are working on it to improve the kanban/taskboard panel. For the next release we will finish:

https://tree.taiga.io/project/taiga/us/1775?kanban-status=211690
https://tree.taiga.io/project/taiga/us/3166?kanban-status=211690
https://tree.taiga.io/project/taiga/us/2928?kanban-status=211690

**Comment by sgtmcg** [comment]
@bameda are you getting  close to that "next release"  This feature would be very beneficial for my team.

**Comment by bameda** [comment]
We are finishing this featured and starting with epics, that is the last functionality for next release. I hope we can release it in August but I don't now, maybe after or before

**Comment by bameda** [comment]
This PR have no sense since https://github.com/taigaio/taiga-front/pull/1073 

Thank you very much @ahhhkah .

**Pull request closed without merging**
