### PR TITLE
Adding Portuguese-BR Translation

### PR DESCRIPTION
**Pull request by iagosenefonte**

### CODE REVIEW

**Comment by prkstaff** [comment]
Brazilian here, nice translation!

**Comment by juanfran** [comment]
thank you very much @iagosenefonte nice work! but we are using transifex for the translatios.

Could you please add the translation there?

https://www.transifex.com/taiga-agile-llc/
https://taiga.io/support/how-can-i-contribute-to-taiga/

**Comment by prkstaff** [comment]
100% translated

**Comment by prkstaff** [comment]
What are the requirements to provide the translation?

**Comment by bameda** [comment]
it's at 70%. You have to translate front and back bacause back has emails, form errors....

**Comment by bameda** [comment]
I reject this PR

**Comment by bameda** [comment]
@prkstaff @iagosenefonte I've added pt_BR locales to taiga for next release. Good work!! 
:dancers: :dancers: :dancers: 

https://github.com/taigaio/taiga-front/commit/57033c6e8be3f02e394ccc19971625880bea3322
https://github.com/taigaio/taiga-back/commit/cf630318443634f1509a25e41b634c818e6152a8

**Comment by prkstaff** [comment]
Thank you

**Pull request closed without merging**
