### PR TITLE
Add check classes for contrib.scss

### PR DESCRIPTION
**Pull request by astagi**
I need these classes for notify option in HipChat plugin: https://github.com/taigaio/taiga-contrib-hipchat/tree/feature/notify

### CODE REVIEW

**Comment by superalex** [comment]
Could you please check the linter is passing "gulp scss-lint --fail"?

**Comment by astagi** [comment]
@superalex yeah sorry, there was an error on properties order :) now it's updated

**Comment by superalex** [comment]
Thank you very much @astagi :+1:

**Comment by astagi** [comment]
no problem :smile:

**Pull request merged**
