### PR TITLE
Improve the tooltips of the burndown graph

### PR DESCRIPTION
**Pull request by bameda**

### CODE REVIEW

**Comment by superalex** [comment]
I think at the beginning of Taiga we implemented the ticks but we had to remove it because some names were long, and text was unreadable very soon.

Could you take the same screenshot but with the smallest resolution we support?.

**Comment by bameda** [comment]
I fix that.

**Comment by superalex** [comment]
What should be happening now?, I don't see any sprint name...

**Comment by bameda** [comment]
I change the tooltips of the points to show the real sprint name instead of a number

Ex.  ```"Optimal pending points for sprint \"{{sprintName}}\" should be {{value}}"```

**Comment by superalex** [comment]
I see but the attached screenshot shows a purple box around some texts that I don't see...

**Comment by bameda** [comment]
What attached screenshot?

**Comment by superalex** [comment]
The one from your first comment

**Comment by bameda** [comment]
It's deleted

**Comment by superalex** [comment]
Ok!, thanks!

**Comment by superalex** [comment]
Great! :+1:

**Pull request merged**
