### PR TITLE
Us/2119/get in touch

### PR DESCRIPTION
**Pull request by Xaviju**
Merge with https://github.com/taigaio/taiga-back/pull/867

### CODE REVIEW

**Comment by Xaviju** [comment]
This PR is already combined and should be merged in three commits.
Or shoud I merge the changelog and the code?
The image should go in a separate commit, no doubt.

**Comment by bameda** [comment]
Maybe you can merge `Update changelog` with `Get in touch with project admins`

And about 'Update looking for people image' maybe you can cherry-pick in master and stable branches and we can upgrade taiga.io with this change.

You choose.

**Comment by Xaviju** [comment]
Done, two commits!!

**Comment by Xaviju** [comment]
14 days ago... :cry:

**Comment by superalex** [comment]
Thank you very much! :+1:

**Pull request merged**
