### PR TITLE
Archived userstory status

### PR DESCRIPTION
**Pull request by superalex**

### CODE REVIEW

**Comment by jespino** [comment]
When I toggle the Show closed sprints and Hide closed sprints, allways make a call for get sprints. Isn't necesary. I can make I request for open sprints first time, one with all when open closed sprints (or better, one getting the closed only) and after that, only show or hide.

**Comment by jespino** [comment]
Needs a rebase from master to merge.

**Comment by bameda** [comment]
and... UPDATE THE CHANGELOG!!!!!!!

**Comment by superalex** [comment]
Working on it right now! :)

**Comment by superalex** [comment]
@jespino: 
- the milestones filtering isn't related to this PR, this one only affects the Kanban part
- rebase done

@bameda 
- sorry, I forgot about it :(, now it's updated

**Comment by bameda** [comment]
@superalex :kissing_cat:

**Comment by jespino** [comment]
:+1:

**Pull request merged**
