### PR TITLE
When dragging a User Story to a Sprint, use the entire Sprint box to accept drag

### PR DESCRIPTION
**Pull request by superalex**

### CODE REVIEW

**Comment by jespino** [comment]
When I try to put USs in an empty closed sprint doesn't work.

**Comment by jespino** [comment]
Have sense that a sprint without USs is closed?

**Comment by superalex** [comment]
Fixed!

**Comment by jespino** [comment]
I like it! :heart:

**Comment by lordloh** [comment]
How will this work if there are multiple sprints? (Multiple future sprints).

**Comment by Xaviju** [comment]
@lordloh It is already working like this. Dragging into the sprint box will add a user story to the sprint.

**Comment by lordloh** [comment]
@Xaviju - No. The box remains in the corner and is scrolled out of view. I am asking a selected sprint box to take the CSS fixed type of position that will remain in view as I scroll though the tasks

capture

**Pull request merged**
