### PR TITLE
Change popover hover color to white.

### PR DESCRIPTION
**Pull request by rsanchezbalo**
Solving this issue:
https://tree.taiga.io/project/taiga/issue/1963

### CODE REVIEW

**Comment by juanfran** [comment]
when i click on type/status/... in a user story detail the hover doesn't work in the popover

**Comment by rsanchezbalo** [comment]
Fixed.

**Comment by Xaviju** [comment]
I don't really like the solution because is too specific and not maintainable.
1. I would try to add this case event in the *popover mixin* generic for all events
    &.active:hover {
        color: $white;
    }
2. Since its part of the mixin, we can remove the unrelevant a styles from the *us-detail.scss* and *lightbox.scss* (o in any other part)

**Comment by superalex** [comment]
Is this one ready to merge? (includes tag but after reading the comments I don't really know...)

**Comment by Xaviju** [comment]
Sorry, not yet!

**Pull request merged**
