### PR TITLE
us/2130,2117,2118,2122/Like, vote and watch stories, task, issues, and projects

### PR DESCRIPTION
**Pull request by bameda**
- https://tree.taiga.io/project/taiga/us/2117
- https://tree.taiga.io/project/taiga/us/2118
- https://tree.taiga.io/project/taiga/us/2122
- https://tree.taiga.io/project/taiga/us/2130

### CODE REVIEW

**Comment by Xaviju** [comment]
What else do we need to merge this Story?

**Comment by bameda** [comment]
- [ ] Divide likes list in likes + votes
- [ ] Your refactor of vote button

**Comment by Xaviju** [comment]
We should talk about the second task in the daily meeting.

**Comment by bameda** [comment]
okidoki

**Comment by bameda** [comment]
I think it's ready to test and merge

**Comment by superalex** [comment]
I think total votes aren't working propery in backlog:

image

The placeholder for empty likes/votes/watchs says: "IT LOOKS LIKE NOTHING WAS FOUND WITH YOUR SEARCH CRITERIA. Maybe try one of the tabs above or search again", this text works for empty results when filtering them but not for the initial empty situation.

**Comment by superalex** [comment]
Great!, I've fixed the taiga-back part and now it's working properly.

@Xaviju, @bameda suggests using this text for both cases, empty search results and no content:

image

I think it looks great, if you validate it I think this one is ready to merge :+1:

**Comment by superalex** [comment]
Great!!!!

**Comment by Xaviju** [comment]
GREAT, GREAT, GREAT!!!

**Pull request merged**
