### PR TITLE
Add url formatting to the markdown wysiwyg editor

### PR DESCRIPTION
**Pull request by astagi**
I couldn't insert an image like this http://199.101.98.242/media/shots/95794-Day_Of_The_Tentacle_(CD_Dos)-3.jpg

:)

### CODE REVIEW

**Comment by Xaviju** [comment]
:__________________) I would accept this just because the image attached.

**Comment by astagi** [comment]
:D :D :D

**Comment by bameda** [comment]
Merged manually https://github.com/taigaio/taiga-front/commit/810eefefc8d83fa9a76451aff18273df6580d2fb

Thank you :+1:

**Comment by astagi** [comment]
yw :smile:

**Pull request closed without merging**
