### PR TITLE
Improve plugin and config loading

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Comment by juanfran** [comment]
I think the `loader.coffee` should have another name because we have another "loader" that does another totally different thing

**Comment by juanfran** [comment]
Why is neccesary a `defaultConf.json` file? Could be inside the `loader.coffee`?

**Comment by juanfran** [comment]
Now `app.js` doesn't have the "version" parameter, could we have cache problems?

**Comment by jespino** [comment]
Great comments :+1: I can fix all :smile:

**Comment by jespino** [comment]
Applied the changes :smiley:

**Comment by juanfran** [comment]
great work! :smile:

**Pull request merged**
