### PR TITLE
Account activation feature

### PR DESCRIPTION
**Pull request by lmarie23**
Send an email at registration with an activation token

It goes with https://github.com/taigaio/taiga-back/pull/1340

### CODE REVIEW

**Comment by alexhermida** [comment]
@lmarie23 this is a feature that we didn't develop on purpose and it isn't a requirement for Taiga. We can evaluate within the team to add it as something optional and configurable for custom instances like public registration feature.

**Comment by SantosSi** [comment]
I think this feature perfectly complements a state of the art security concept by avoiding impersonation and adding a state-of-the-art opt-in mechanism. A software like this should have this at least available to be activated when required, if not active by default and ready to be deactiavted.
It also improves the Taiga's security impression. Good function.

**Comment by lmarie23** [comment]
@alexhermida I have put a boolean to activate the featyre in the backend settings.

**Comment by migonzalvar** [comment]
We added the validated email feature some weeks ago.

Currently, this is used only to prevent user to add members to projects. In the future could be used to restrict other actions.

**Pull request closed without merging**
