### PR TITLE
Adding attachments on creation

### PR DESCRIPTION
**Pull request by Xaviju**
Still to be done:

- [x] Add selection to local storage
- [x] Add attachment image if there is image
- [x] Add file image if it is not an image
- [x] Review Styles

### CODE REVIEW

**Comment by Xaviju** [comment]
Remember to add this feature to the release docs!

**Comment by bameda** [comment]
TODO: 
- [ ] Update CHANGELOG (one commit)
- [ ] Merge commits (wip, tmp...)

**Comment by bameda** [comment]
We have to fix CHANGELOG file and mix the two 1.10 sections before merge.

**Comment by Xaviju** [comment]
@bameda this is ready to merge but cannot be merged until:
- [ ] Fix&add to changelog
- [ ] Mix sections 1.,10
- [ ] Test extensively

How to test:
- Attachments have two views, list and gallery
- Attachments can be drag&dropped from desktop to descriptions and comments, including wiki
- If there are no attachments, there is a message letting you drop on it.

**Comment by Xaviju** [comment]
@bameda bugs solved

**Pull request merged**
