### PR TITLE
fixing pre-commit hook failure due to scss-lint warnings 

### PR DESCRIPTION
**Pull request by reduxionist**
I will update this PR (if desired) once I know the desired approach to the remaining instances of the issue.

Symptom:
The scss-lint task invoked by the pre-commit hook fails, blocking commits unless --no-verify is passed.

Cause:
Two lint rules fail across 14 files: 20 ColorVariable and 17 ImportantRule warnings.
(The attached PR fixes 3 of the ColorVariable warnings by replacing color literals with color variables already defined in app/styles/dependencies/colors.scss)

Possible Solutions:

1. The simplest approach would be to override the default scss-lint config by setting enabled to false for these two linters in .scss-lint.yml. It's clean but future committers will not be notified if they introduce new code that violates these two best practices.

2. The most pedantic approach would be to add inline comments disabling the ImportantRule linter for those blocks that use it, and either do the same for blocks that use color literals or create variables for each color literal used and thus avoid that warning. (Note, however, that 11 of the 14 remaining (after this PR) literal color references are used only once, and the remaining three are only used twice. An even more nuanced approach would be to create variables for just the three duplicated literals and use inline comment exemptions for the rest.)

Let me know, how, if at all, I should proceed further.

### CODE REVIEW

**Comment by Xaviju** [comment]
Hi @reduxionist 
We also have the same scss-lint fail after update the scss-lint gem. Thanks for taking this issue.
 
Our approach:

1. For the ```ColorVariable``` rule, I think we should fix it because its a good practice to have every color in a variable, and check if by mistake we used a color that its not defined, but could be. (like, imagine, we used a gray shade, but we already have a very similar shade)
2. For the ```importantRule``` I prefer to keep it(to avoid unnecesary importants), but exclude the typography.scss file because it is required by the @fontface generated css code. Another approach is to move the @fontface code to another file and exclude this new file.

Let us know what do you think and if you will proceed with the fixes. We would like to fix it as soon as possible so no Taiga developers have this problem. :)

**Comment by reduxionist** [comment]
Hi Xaviju,

I will proceed with the fixes as per your preferred approach.

I will squash the commit that started this PR, which fixed the three literals with existing color names, into an upcoming commit fixing all color literals to keep the commit history simple.

Thanks for the prompt reply,
Jonathan

**Comment by Xaviju** [comment]
Nice, thanks a lot :+1:

**Comment by reduxionist** [comment]
The ColorVariable warnings have now been fixed, I squashed the previous partial-fix commit into the commit fixing the remainder, and GitHub has correctly updated the PR to reflect them as a single commit.

Only a handful of the color literals had official names (these were the gray60, gray80, etc., grays) for their exact values. For the rest I prefixed the closest matching standardized color name with the dominant hue of the color so they're easy to recognize. The variations were too significant to use a simple "[very-](light|dark)" type naming scheme. If you prefer some alternative scheme though, just let me know, I wrote a one-liner to automate the whole update process so any desired changes will be trivial to implement.

You'll see that there are a ton of grays in use; this does seem likely to be an area where your designers can consolidate on a smaller subset of values.

I'm about to implement the important rule next. I don't intend to split out the @fontface code into a separate file because there are two other blocks in typography.scss (for Taiga icons IIRC) that also use !important, so that wouldn't solve the issue. Instead I'll use inline comments to disable that particular linter for just those blocks that currently use !important, preventing any further use from going unnoticed. I will also use block-specific exemptions for the single use in base.scss and for the four uses in elements.scss, unless instructed otherwise.

**Comment by reduxionist** [comment]
ImportantRule block-scope exemptions now added.

Pre-commit hook now executes successfully! :)

**Comment by Xaviju** [comment]
**Looks good to me!** 
I'll add a couple issues in Taiga to refactor the color variables. It seems to me that we have too many shades of gray.
I will also take a look at those ```!importants``` to ensure that they are really important.

Thanks! :+1:

**Pull request merged**
