### PR TITLE
correction : grammatical error in invitation page for french translation

### PR DESCRIPTION
**Pull request by eldk**
Hello,

Corrected some grammatical error in invitation page french translation.

Thanks,

Eric

### CODE REVIEW

**Comment by jespino** [comment]
Sorry but for fix translations you have to use transifex.

I fix it at "https://www.transifex.com/taiga-agile-llc/taiga-front/translate/#fr/locale-enjson/45192319?qt=vous a invité"

You can use transifex to fix more typos or to help us with the translations.

Thank you.

**Comment by eldk** [comment]
Hello,

Those chain are not in transifex.

I have done some translations for the one that are in transifex, in transifex.

Thanks,

Eric

**Comment by jespino** [comment]
Maybe in September weren't there, but I have changed it today.

**Comment by eldk** [comment]
Ok, I will do it in Transifex,
Thanks.

**Pull request closed without merging**
