### PR TITLE
Fixed a bug where the profile avatar resolution would be scaled down

### PR DESCRIPTION
**Pull request by natrist**
User profile avatars are currently scaled down and it results in bad image quality.
This PR fixes this by forcing the 'big' resolution (300x300) for the user profile section.

### CODE REVIEW

**Comment by natrist** [comment]
I also fixed another related bug with the user profile settings menu.
See second commit for code: https://github.com/thejobelrepos/taiga-front/commit/7426968f07c9819d198c7f684ed44ec8f95066cd

I would have kept both changes under the same commit, but did not realize the bug was affecting another menu. Sorry!

**Comment by natrist** [comment]
@superalex Is this being looked into? I see other PRs with no answer for days.

**Comment by migonzalvar** [comment]
Thank you @natrist .

We will look into this pull request and https://github.com/thejobelrepos/taiga-front/commit/7426968f07c9819d198c7f684ed44ec8f95066cd as soon as possible.

**Comment by migonzalvar** [comment]
Thank you @natrist

**Pull request merged**
