### PR TITLE
US#1913: CSV Reports

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Comment by superalex** [comment]
Is this one ready to merge?

**Comment by juanfran** [comment]
- The enter submit doesn't work.
- In the export section, the icon doesn't match with its behavior and it's inconsistent with the same button in the github section.
- Add new should focus on a field.
- When adding a duplicate name I get two errors, one inline and one global. I think the global should be removed.

**Comment by jespino** [comment]
@juanfran Which enter submit doesn't work?

**Comment by bameda** [comment]
Links "How to use this on my own spreadsheet?" are not working

**Comment by superalex** [comment]
I think it should be a link to taiga support...

**Comment by bameda** [comment]
Yep, but href is empty

**Comment by superalex** [comment]
We could create the empty page in taiga support, fill the href and then fill the page before the release.

**Comment by jespino** [comment]
Agree!

**Pull request merged**
