### PR TITLE
Excluding closed sprints by default

### PR DESCRIPTION
**Pull request by superalex**

### CODE REVIEW

**Comment by jespino** [comment]
El spinner no gira, hay que comprobar por qué.

**Comment by superalex** [comment]
I think the spinner "thing" is related to everything in Taiga, it's not only a problem of this branch

**Comment by Xaviju** [comment]
If there are no closed sprints, 'Show closed sprints' button should not be visible.

**Comment by Xaviju** [comment]
Button is being designed as well :)

**Comment by Xaviju** [comment]
Looks ready to me if @superalex has finished the backend fixes as well :ear:

**Comment by superalex** [comment]
Backend part is finished and merged :)

**Pull request merged**
