### PR TITLE
Add custom themes \o/

### PR DESCRIPTION
**Pull request by astagi**

### CODE REVIEW

**Comment by astagi** [comment]
I forgot to specify that you need to list available themes in config at the momenti. My current config is:

    {
        "api": "http://localhost:8000/api/v1/",
        "eventsUrl": null,
        "debug": true,
        "publicRegisterEnabled": true,
        "feedbackEnabled": true,
        "privacyPolicyUrl": null,
        "termsOfServiceUrl": null,
        "maxUploadFileSize": null,
        "gitHubClientId": null,
        "contribPlugins": ["/js/slack.js", "/js/hipchat.js"],
        "themes": ["taiga", "nephila"],
    }

**Comment by bameda** [comment]
Ok, I have to test and review it carefuly but looks awesome. Thanks to both of you.

**Comment by astagi** [comment]
Thanks @bameda

**Comment by bameda** [comment]
I close this PR because I've made a new one with some refactors and fixes https://github.com/taigaio/taiga-front/pull/504

@astagi could you review this commit (https://github.com/taigaio/taiga-front/commit/e7f4823947e29dc46b95c7c10b2468eb90b8af52) to give me your Ok? then I'll make fixup of mi changes with your previos commit.

**Comment by astagi** [comment]
Wow you wrapped anything in a service, looks nice :) I'll test it deeply tomorrow and ket you know!

**Pull request closed without merging**
