### PR TITLE
Sidebar refactor

### PR DESCRIPTION
**Pull request by Xaviju**
Fixes to do:

- [x] Remove popover in header on status change when click out
- [x] Add watchers button stopped working (it has been removed from watchers list directive)
- [x] Check if ticket is editable before adding watchers
- [x] Review its full functionality. 

It should be reviewed by @elhombretecla as well

### CODE REVIEW

**Comment by Xaviju** [comment]
This is ready to merge, its depends on the ninja release.
How to test:
- Test sidebars in issues, tasks and stories.
- Test status selector
- Test watchers selector
- Test settings button at the bottom

**Comment by bameda** [comment]
Sidebar must be review as public/no-edit-permission user:
- There are some errors with styles.
- There are some objects shown as a clicked element but they aren't (us points, buttons, assigned to)

image

**Comment by bameda** [comment]
@Xaviju i fix all we talk and I remove some unnecesary success confirm messsages... but i found one more error (Maybe you do not think the same ;-)) I can't add tags.

image

**Comment by Xaviju** [comment]
Yihaaa!! :cow:

**Pull request merged**
