### PR TITLE
Tribe buttons

### PR DESCRIPTION
**Pull request by Xaviju**
**WARNING** Please do not merge until ```us/3536/tribe-integration``` is merged in master and master is rebased

### CODE REVIEW

**Comment by Xaviju** [comment]
Is this ready for test?

**Comment by superalex** [comment]
I think it's ready but we still can't merge, we have to wait until the official tribe announcement ;)

**Comment by Xaviju** [comment]
Sure, sorry I did not read my own comment :S

**Comment by Xaviju** [comment]
This could be already merged but I would wait until SVG icons get merged and then some fixes to this branch should be done

**Comment by bameda** [comment]
is a test

**Pull request merged**
