### PR TITLE
Add word-break rule in .kanban-task

### LINKED ISSUE #1014: Task-text is shown badly in some cases.
captura de pantalla 2016-05-20 a las 1 07 01

As you can see in the picture, task text overflows kanban-task div

A simple fix could be adding the following rule to the [kanban-task.scss](https://github.com/taigaio/taiga-front/blob/0fd334398fe2432595be3bb9c0a9338a6498f21b/app/styles/components/kanban-task.scss)

```css
.kanban-task {
    word-break: break-word;
}
```

Resulting in:
captura de pantalla 2016-05-20 a las 1 18 47

### PR DESCRIPTION
**Pull request by IagoLast**
This closes #1014

### CODE REVIEW

**Comment by Xaviju** [comment]
Does not it makes sense to add it to the ```.task-name```
```
.task-name {
        @include font-type(bold);
        word-break: break-word;
 }
```
instead of the full card? 

I think this should be done as well in ```taskboard-task.scss```

Great fix!

**Comment by IagoLast** [comment]
@Xaviju  let me know what you prefer and i´ll do :)

**Comment by Xaviju** [comment]
We are currently working on a new design for this cards so soon we will refactor them. This code will not last long as it is now: https://tree.taiga.io/project/taiga/us/2928?kanban-status=211690
But, as this code will be the reference for the improved UI card I guess it would be better to be added to the element ```.task-name``` because its more easily understandable on what it does exactly.

Anyway your opinion is as important as mine since this is your PR! :D

**Comment by IagoLast** [comment]
@Xaviju done

**Comment by Xaviju** [comment]
Thanks!
Your PR will be merged here: https://github.com/taigaio/taiga-front/pull/1019

**Pull request closed without merging**
