### PR TITLE
Allow to include anchor links in the wiki pages

### PR DESCRIPTION
**Pull request by jespino**
Needs the PR#367 of taiga-back

### CODE REVIEW

**Comment by jespino** [comment]
I'm almost sure there are a better way to do this.

**Comment by bameda** [comment]
Mmmmmm, this happends in all the markdown fields:

- wiki.content
- us/task/issue.description
- historyItem.comment

and you only fis it for the first case.

**Comment by jespino** [comment]
Ok, I will take a look of this fields too. Thanks! :smile:

**Comment by bameda** [comment]
https://docs.angularjs.org/api/ng/service/$anchorScroll

http://stackoverflow.com/questions/14712223/how-to-handle-anchor-hash-linking-in-angularjs

**Comment by jespino** [comment]
I tried to use the $anchorScroll service but doesn't work, I will ask @juanfran which solution he prefer.

**Comment by juanfran** [comment]
we will redo the wysiwyg soon so we could merge this and when we have the new wysiwyg find another solution

**Comment by superalex** [comment]
I agree, who will do the honors? :)

**Pull request merged**
