### PR TITLE
Wiki nav redesign

### PR DESCRIPTION
**Pull request by Xaviju**
- Renamed **links** to **bookmarks**
- Redesigned links area

### CODE REVIEW

**Comment by Xaviju** [comment]
prwiki

**Comment by bameda** [comment]
@jespino some TODOs here

- [ ] After creating new bookmarks I can't sort them.
- [ ] The new bookmark input is showing in a randomly place

**Comment by jespino** [comment]
@juanfran can you review the last commit to ensure that the approach is correct? I have inserted the dragula initialization and stopping in the render function.

**Comment by juanfran** [comment]
todo @Xaviju 
- squash
- styling the drag and drop

**Comment by Xaviju** [comment]
Baboom! :boom:

**Pull request merged**
