### PR TITLE
Seo 

### PR DESCRIPTION
**Pull request by bameda**

### CODE REVIEW

**Comment by superalex** [comment]
@bameda are you still working on this?

**Comment by bameda** [comment]
Yep, I need to fix the tests

**Comment by juanfran** [comment]
the <title> is broken in all the statuses  in admin/attributes/(points/priorities/severities)

 " - Project values - Project Example 0"

**Comment by juanfran** [comment]
admin/integration/webhooks has an incorrect title "Custom Fields - Custom Attributes - "

**Comment by juanfran** [comment]
I don't know if it's good that all the pages have the same keywords

**Comment by juanfran** [comment]
`$scope is not defined` in US detail

**Comment by bameda** [comment]
Keywords meta is no longer important.

I'll fix this titles

**Comment by juanfran** [comment]
I think we should cut off the wiki content in the meta description

**Comment by bameda** [comment]
@juanfran I fix all, except '$scope is not defined in US detail' because I cann't reproduce it.

**Comment by juanfran** [comment]
@bameda taiga throw the error in a US with tasks

detail.coffee line 69, $scope doesn't exist, it's @scope

**Comment by bameda** [comment]
Ok, I'll fix

**Comment by bameda** [comment]
Fixed!! :dancers:

**Pull request merged**
