### PR TITLE
Add custom themes \o/ (based on Astagi feature/newthemes)

### PR DESCRIPTION
**Pull request by bameda**
Minor fixes over https://github.com/taigaio/taiga-front/pull/489

### CODE REVIEW

**Comment by astagi** [comment]
@bameda imho this is "ready for merge" :) I also started the official Nephila's theme, it works great! https://github.com/nephila/nephila-taiga-theme

**Comment by bameda** [comment]
Ok, we had already closed the next release (1.8) that it will be ready this week and we we would like to add some example themes (high contrast, bigger texts...). So I'll merge this PR for the next release (1.9).

**Comment by astagi** [comment]
Nice! :+1: @bameda are you working on these themes or can I ask to my team to try to create new ones and open PR upon this branch?

**Comment by bameda** [comment]
We have not yet started. @Xaviju could be probably the responsible for makeing them when he has some free time but feel free to propose all the themes you want. PRs are welcome!!

**Comment by bameda** [comment]
BTW I'll resolve the conflicts of this branch with master tomorrow

**Comment by Xaviju** [comment]
@astagi @bameda its amazing, I love to be able to create themes. :sob: 
Currently creating themes based on the variables files its easy, but hard to create a good looking site. I am going to refactor it as much as possible to offer a kind of flexible framework (somehow like bootstrap or other frameworks do) so other users can create full usable themes.
Lets help UI developers join the contributions team in Taiga :tada:

**Comment by Xaviju** [comment]
I've just uploaded a custom Material Design Theme and a full framework refactor. Could you please @bameda and @astagi test it (only if you can)?
I am going to try to create a High contrast theme as well before merging.

**Comment by Xaviju** [comment]
@bameda each time I logout and login with a user and a theme I have to choose again the theme in the user profile.

**Comment by bameda** [comment]
@Xaviju it's good for me, but I have found some errors in the admin panel with the second menu

**Comment by Xaviju** [comment]
@bameda which theme, what problem? Did you check the issue I wrote or do you prefer an issue in Taiga for you? :8ball:

**Comment by bameda** [comment]
image

image

**Comment by Xaviju** [comment]
Fixed!

**Comment by Xaviju** [comment]
@bameda bugs fixed!

**Pull request merged**
