### PR TITLE
Fix hidden class to works correctly with safari

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Comment by Xaviju** [comment]
Sorry, this cannot be merged, this is not a good solution for multiple reasons. :bomb: 
In terms of a hidden DOM element using visibility:hidden instead of display:none, it made me think of this:

image
image
image

**Comment by superalex** [comment]
:(

What other alternatives do we have?

**Comment by Xaviju** [comment]
The solution requires working on submit buttons to have same styles always. Fast solutions like this will be always technical debt, and in this case, our system could simply explode. :)

Solution is going to be a little bit slower but probably better.

**Comment by superalex** [comment]
I fully understand but, are you sure we can have the same css styling for submit buttons than for hrefs?

**Comment by Xaviju** [comment]
I think we can. If we couldn't for every browser, I think we have to do something else or keep the bug in those browsers. 
We can not merge this solution, sorry.

**Comment by superalex** [comment]
Well, I've seen it's the one recommended in a lot of internet sites but it's a bit ugly

In case the button solution doesn't work I don't completely like the idea of keeping the bug failing for those browsers...

**Comment by jespino** [comment]
Completely agree with @superalex if we have a better solution great, but we need a solution. If this is a ugly patch, we can try to make the patch more controlled, moving it to shame.scss or a set of css only for safari fixes.

**Comment by Xaviju** [comment]
**There are basic code quality red lines. This is a big one for me.** 
I assume the responsibility of fixing that for the browsers. If you accept this PR it's against my opinion.

**Comment by juanfran** [comment]
totally agree with @Xaviju, let us try other solutions

**Comment by jespino** [comment]
It isn't about "This" pull request, is about find a solution, if isn't posible a good one, must be a ugly one.

**Comment by jespino** [comment]
This PR is rejected for search a better solution.

**Pull request closed without merging**
