### PR TITLE
chore: relicense to AGPL

### PR DESCRIPTION
**Pull request by bameda**

### CODE REVIEW

**Comment by ChriFo** [comment]
Will you inform your community about the reasons for this change?

I found this [article](https://community.taiga.io/t/whats-taigas-open-source-license/138) on community.taiga.io but obviously you changed your mind.

**Comment by bameda** [comment]
Hi @ChriFo, 

MPL is incompatible with one of the components used by taiga-front and that is why we have to go back to AGPL, at least in the frontend app.

**Comment by ChriFo** [comment]
Thanks for the info @bameda. 
So my not public fork from years ago is also violating the license? Can you name the component with the license which is not MPL compatible?

**Comment by bameda** [comment]
Should not, sspecially if you do not make commercial use. And the incompatibility with future versions will not become effective for a couple of days. 

The component is the WYSIWYG text editor (https://github.com/taigaio/taiga-html-editor).

**Pull request merged**
