### PR TITLE
fix 'show closed sprints' visibility

### PR DESCRIPTION
**Pull request by juanfran**
test with https://github.com/taigaio/taiga-back/tree/issue/2851/closed_milestones_errors

### CODE REVIEW

**Comment by superalex** [comment]
Error detected when:
 - I have a closed sprint
 - Click on "show closed sprint"
 - D&D a US to the closed sprint

Result: the sprint is duplicated

**Comment by juanfran** [comment]
fixed!

**Comment by superalex** [comment]
Two more failing cases:
 - Dragging a closed us to an empty sprint
 - Deleting a closed sprint

**Comment by superalex** [comment]
Great!

**Pull request merged**
