### PR TITLE
prevent location search if the url has the same parameters

### PR DESCRIPTION
**Pull request by juanfran**

### CODE REVIEW

**Comment by superalex** [comment]
And if another class uses the mixin without adding the isInCurrentRouteParams method? why not adding isInCurrentRouteParams in the mixin?

**Comment by juanfran** [comment]
because then I have to import "$route" on all controllers that use this mixin

**Comment by superalex** [comment]
And if another class uses the mixin without adding the isInCurrentRouteParams method?

**Comment by superalex** [comment]
And if the mixing has a default implementation of the method? (without using $route)

**Pull request merged**
