### PR TITLE
Enhancement/3366/story format

### PR DESCRIPTION
**Pull request by Xaviju**
Based on enhancement: 
https://tree.taiga.io/project/taiga/issue/3366

### CODE REVIEW

**Comment by Xaviju** [comment]
What do you guys think?

**Comment by bameda** [comment]
It is not so easy because with your change the placeholder for task description and issue description will be the same as story description.

**Comment by allistera** [comment]
Also as this is a placeholder it will disappear as soon as the user starts entering text, loosing perhaps the main reason for the change (To attempt to loosely enforce a user story template). 

Perhaps a better solution would be to have some sort of user story/tasks/issues templates? 

Either in the form of a drop down box or an icon in the WYSIWYG editor that lists admin defined templates.

**Comment by Xaviju** [comment]
We could remove this PR and promote the issue to Story. We could think the best way to do this. I thought this was a quick win :\

**Comment by bameda** [comment]
I agree

**Pull request closed without merging**
